#!/usr/bin/env zsh

#############################################################################################
# brit.sh                                                                                   #
#                                                                                           #
# AUTH: pradesigner                                                                         #
# VDAT: v1 - <2023-07-31 Mon>                                                               #
# PURP: get broot to run                                                                    #
#                                                                                           #
# A script to launch broot and then get back into the directory from which it was launched. #
# It has had limited success and is useless for our purposes.                               #
#############################################################################################




########
# Help #
########
if [[ $1 == '-h' ]]; then
    echo "use: A script to launch broot and then get back into the directory."
    echo "how: jri"
    exit
fi

#source "~/.zshrc"

########
# Main #
########

# This script was automatically generated by the broot program
# More information can be found in https://github.com/Canop/broot
# This function starts broot and executes the command
# it produces, if any.
# It's needed because some shell commands, like `cd`,
# have no useful effect if executed in a subshell.
function br {
    local cmd cmd_file code
    cmd_file=$(mktemp)
    if broot --outcmd "$cmd_file" "$@"; then
        cmd=$(<"$cmd_file")
        echo "cmd: $cmd"        
        command rm -f "$cmd_file"
        eval "$cmd"
    else
        code=$?
        echo "code: $code"
        command rm -f "$cmd_file"
        return "$code"
    fi
}


br
zsh


exit



#########
# Notes #
#########

